### ISSUE TITLE
modpack Large Centrifuge NEI crash

### ISSUE THREAD

**Issue by bHXDgiuMa5yLHyC8** [draknyte1/GTplusplus#275]
https://pastebin.com/cq0WbT8m

This happened when I clicked on the GT saw metatool in NEI using prerelease 15 early. It doesn't happen in a much smaller test pack.

**Comment by draknyte1** [comment]
Fixed by https://github.com/draknyte1/GTplusplus/pull/271. 

I suggest testing with pre15 available on discord. As I have no idea what version you're using.

**Comment by bHXDgiuMa5yLHyC8** [comment]
That was the version I was using.

**Comment by draknyte1** [comment]
How am I meant to know? 

You haven't given any of the information I require for issue reports. This is definitely fixed in the latest prerelease.

**Comment by bHXDgiuMa5yLHyC8** [comment]
Sorry, I did not know there was an issue template. I said I was using "prerelease 15 early" in the initial post. I downloaded and tried it again and I am still getting the same crash.

https://pastebin.com/3LwRDf86

**Comment by draknyte1** [comment]
Something is registering bad recipes.
Shouldn't crash anymore.
